src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Security\Core\User\UserInterface;//追記
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;//追記

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("username")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActivated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getIsActivated(): ?bool
    {
        return $this->isActivated;
    }

    public function setIsActivated(bool $isActivated): self
    {
        $this->isActivated = $isActivated;

        return $this;
    }

    //以下、追記
    public function __construct(){
        $this->isActivated=true;
    }

    public function getSalt(){
        return null;
    }

    public function getRoles(){
        if($this->username=='admin'){
            return ['ROLE_ADMIN'];
        }
        else{
            return ['ROLE_USER'];
        }
    }

    public function eraseCredentials(){
        
    }

    public function serialize(){
        return serialize([
            $this->id,
            $this->username,
            $this->password,
            $this->isActivated,
        ]);
    }

    public function unserialize($serialized){
        list(
            $this->id,
            $this->username,
            $this->password,
            $this->isActivated,
        )=unserialize($serialized,['allowed_classes'=>false]);
    }
}

src/Controller/HelloController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\Security\Core\Exception\AccessDeniedException;

use App\Entity\Person;

class HelloController extends AbstractController{
    /** 
     * @Route("/hello", name="hello")
     */
    public function index(Request $request){
        if(!$this->getUser()->getIsActivated()){
            throw new AccessDeniedException('アクセス権がありません');
        }
        return $this->render('hello/index.html.twig',[
            'user'=>$this->getUser(),
        ]);
    }

    /**
     * @Route("/other/{domain}",name="other")
     */
    public function other(Request $request ,$domain=""){
        if($domain==""){
            return $this->redirect("/hello");
        }
        else{
            return new RedirectResponse("http://{$domain}.com");
        }
    }

    /**
     * @Route("/form2",name="form2")
     */
    public function form2(Request $request){
        $person = new Person("taro",36,"taro@yamada.com");

        $form = $this->createFormBuilder($person)
          ->add("name",TextType::class)
          ->add("age",IntegerType::class)
          ->add("email",EmailType::class)
          ->add("save",SubmitType::class,["label"=>"Click"])
          ->getForm();

        if($request->getMethod()=="POST"){
            $form->handleRequest($request);
            $obj=$form->getData();
            $msg= <<< EOM
            <ul>
            <li>{$obj->getName()}</li>
            <li>{$obj->getAge()}</li>
            <li>{$obj->getEmail()}</li>
            </ul>
EOM;
        }
        else{
            $msg="名前を書いてね";
        }
       
        return $this->render("hello/form2.html.twig",[
            "message"=>$msg,
            "form"=>$form->createView(),
        ]);
    }

    /**
     * @Route("/session_test",name="session_test")
     */
    public function session_test(Request $request,SessionInterface $session){
        $data=new MyData();

        $form=$this->createFormBuilder($data)
        ->add("data",TextType::class)
        ->add("save",SubmitType::class,["label"=>"click"])
        ->getForm();

        if($request->getMethod()=="POST"){
            $form->handleRequest($request);
            $obj=$form->getData();
            if($obj->getData()=="!"){
                $session->remove("data");
            }
            else{
                $session->set("data",$obj->getData());
            }
        }

        return $this->render("hello/session_test.html.twig",[
           "data"=>$session->get("data"),
           "form"=>$form->createView(),
        ]);

    }
    /**
     * @Route("/getPersonData",name="getPersonData")
     */
    public function getPersonData(Request $request){
        $repository=$this->getDoctrine()
        ->getRepository(Person::class);

        $persons=$repository->findAll();

        return $this->render('hello/getPersonData.html.twig',[
            'title'=>'getPersonData',
            'persons'=>$persons,
        ]);
    }
}

class Person2{
    protected $name;
    protected $age;
    protected $email;

    public function __construct($name,$age,$email){
        $this->name=$name;
        $this->age=$age;
        $this->email=$email;
    }
    public function getName(){
        return $this->name;
    }
    public function setName($name){
        $this->name = $name;
    }
    public function getAge(){
        return $this->age;
    }
    public function setAge($age){
        $this->age = $age;
    }
    public function getEmail(){
        return $this->email;
    }
    public function setEmail($email){
        $this->email = $email;
    }
}

class MyData{
    private $data="";

    public function getData(){
        return $this->data;
    }
    public function setData($data){
        $this->data=$data;
    }
}

templates/hello/form.html.twig
{% import 'macro.html.twig' as m %}

<table>
{{m.input('text','Name','noname')}}
{{m.input('number','Age',0)}}
{{m.input('email','Mail','no@mail')}}
{{m.submit('click')}}
</table>

templates/hello/form2.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        {{message|raw}}
        {{form_start(form)}}
        {{form_widget(form)}}
        {{form_end(form)}}
    </body>
</html>

templates/hello/getPersonData.html.twig
{% extends 'base.html.twig' %}

{% block page %}
{{title}}
{% endblock %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}
<h2>Person一覧</h2>
<table>
<tr>
<th>id</th>
<th>name</th>
<th>mail</th>
<th>age</th>
</tr>
{% for person in persons %}
<tr>
<td>{{person.id}}</td>
<td>{{person.name}}</td>
<td>{{person.mail}}</td>
<td>{{person.age}}</td>
<td>
<ul>
{% for message in person.messages %}
<li>{{message.content}}</li>
{% endfor %}
</ul>
</td>
</tr>
{% endfor %}
</table>
{% endblock %}

templates/hello/index.html.twig
{% extends 'base.html.twig' %}


{% block page %}一般会員用ページ{% endblock %}
{% block title %}一般会員用ページ{% endblock %}

{% block body %}
<h2>一般会員用ページ</h2>

<table>
<tr>
<th>id</th>
<td>{{user.id}}</td>
</tr>
<tr>
<th>名前</th>
<td>{{user.username}}</td>
</tr>
<tr>
<th>メアド</th>
<td>{{user.email}}</td>
</tr>
<tr>
<th>role</th>
<td>{{user.roles[0]}}</td>
</tr>
</table>
{% endblock %}  

templates/hello/session_test.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        data:{{data}}
        {{form_start(form)}}
        {{form_widget(form)}}
        {{form_end(form)}}
    </body>
</html>

templates/hello/table.html.twig
<table>
<tr>
<th>name1</th>
<th>name2</th>
<th>name3</th>
</tr>
{% for array in arrays %}
<tr>
<td>{{array.name1}}</td>
<td>{{array.name2}}</td>
<td>{{array.name3}}</td>
</tr>

{% endfor %}
</table>